### ISSUE TITLE
How does "My components" works?

### ISSUE THREAD

**Issue by stylessh** [pheralb/superui#133]
Been checking around the library and it's great, but I don't get how "my components" section works, it has to be accepted to get into the official component list?

**Comment by nachoaldamav** [comment]
Hi! 

The idea of this funcionality is to make a list of community created components.

We are currently working on this feature and only your own components are visible.

We hope you can enjoy and share your components after the hackathon!

PS: In case you didn't see it, you can create a Component in your profile drop-down.

**Comment by stylessh** [comment]
Alright, that's good.

Yes, I see the button on the dropdown, but I think it'll be better to put a create button in the components screen as well.

I might be creating a PR adding this.
